added shopping cart and cart item entities
MarkGodnyi/my-book-store pull request #8
Opened 2023-10-26 14:00 UTC by MarkGodnyi

2023-10-31 18:42 UTC, Rommelua requested changes

2023-10-31 18:42 UTC, Rommelua commented on src/main/java/store/controller/ShoppingCartController.java
> +@RequestMapping(value = "/cart")
```suggestion
@RequestMapping(value = "/carts")
```

2023-10-31 18:42 UTC, Rommelua commented on src/main/java/store/dto/request/CreateCartItemRequestDto.java
> +    @Max(value = 10)
why?)

2023-10-31 18:42 UTC, Rommelua commented on src/main/java/store/mapper/CartItemDtoMapper.java
> +    default void setShoppingCart(@MappingTarget CartItem cartItem) {
remove this method
Better set SC in Service

2023-10-31 18:42 UTC, Rommelua commented on src/main/java/store/service/CartItemService.java
> +public interface CartItemService {
```suggestion
public interface ShoppingCartService {
```

2023-10-31 18:42 UTC, Rommelua commented on src/main/java/store/service/CartItemService.java
> +    void delete(Long id);
```suggestion
    ShoppingCartDto getById(Long id);

    ShoppingCartDto addToCart(AddToCartRequestDto request, Long id);

    ShoppingCartDto updateCartItem(Long id, Long cartItemId, UpdateCartItemRequestDto request);

    ShoppingCartDto removeCartItem(Long id, Long cartItemId);
```

2023-10-31 18:44 UTC, MarkGodnyi commented on src/main/java/store/dto/request/CreateCartItemRequestDto.java
> +    @Max(value = 10)
Because I have a small shop

2023-11-03 10:49 UTC, Rommelua approved these changes

2023-11-03 10:49 UTC, Rommelua commented on src/main/java/store/security/JwtUtil.java
> +    private static final Long EXPIRATION_TIME_IN_MILLIS = 6000_000L;
```suggestion
    private static final Long EXPIRATION_TIME_IN_MILLIS = 6_000_000L;
```

2023-11-15 15:19 UTC, merged